name: DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug files
        run: |
          pwd
          ls -R

      - name: Build Docker Image
        run: docker build -t devops-app -f docker/Dockerfile .
