name: DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug files
        run: |
<<<<<<< HEAD
          pwd
=======
          echo "Current directory:"
          pwd
          echo "Project structure:"
>>>>>>> be392b3 (remove duplicate workflow)
          ls -R

      - name: Build Docker Image
        run: docker build -t devops-app docker
